// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck

import * as React from 'react'

import { AlarmChecked } from './AlarmChecked'
import { AlarmCheckedBig } from './AlarmCheckedBig'
import { AlarmCheckedBigFilled } from './AlarmCheckedBigFilled'
import { AlarmCheckedFilled } from './AlarmCheckedFilled'
import { AlarmClock } from './AlarmClock'
import { AlarmClockBig } from './AlarmClockBig'
import { AlarmClockBigFilled } from './AlarmClockBigFilled'
import { AlarmClockFilled } from './AlarmClockFilled'
import { Alert } from './Alert'
import { AlertBig } from './AlertBig'
import { AlertBigFilled } from './AlertBigFilled'
import { AlertFilled } from './AlertFilled'
import { ArrowDown } from './ArrowDown'
import { ArrowDownBig } from './ArrowDownBig'
import { ArrowLeft } from './ArrowLeft'
import { ArrowLeftBig } from './ArrowLeftBig'
import { ArrowRight } from './ArrowRight'
import { ArrowRightBig } from './ArrowRightBig'
import { ArrowUp } from './ArrowUp'
import { ArrowUpBig } from './ArrowUpBig'
import { Bag } from './Bag'
import { BagBig } from './BagBig'
import { BagBigFilled } from './BagBigFilled'
import { BagFilled } from './BagFilled'
import { Bell } from './Bell'
import { BellBig } from './BellBig'
import { BellBigFilled } from './BellBigFilled'
import { BellFilled } from './BellFilled'
import { Bookmark } from './Bookmark'
import { BookmarkBig } from './BookmarkBig'
import { BookmarkBigFilled } from './BookmarkBigFilled'
import { BookmarkFilled } from './BookmarkFilled'
import { Calendar } from './Calendar'
import { CalendarBig } from './CalendarBig'
import { CalendarBigFilled } from './CalendarBigFilled'
import { CalendarFilled } from './CalendarFilled'
import { Card } from './Card'
import { CardBig } from './CardBig'
import { CardBigFilled } from './CardBigFilled'
import { CardFilled } from './CardFilled'
import { Charity } from './Charity'
import { CharityBig } from './CharityBig'
import { Chat } from './Chat'
import { ChatBig } from './ChatBig'
import { ChatBigFilled } from './ChatBigFilled'
import { ChatFilled } from './ChatFilled'
import { CheveronDown } from './CheveronDown'
import { CheveronDownBig } from './CheveronDownBig'
import { CheveronLeft } from './CheveronLeft'
import { CheveronLeftBig } from './CheveronLeftBig'
import { CheveronRight } from './CheveronRight'
import { CheveronRightBig } from './CheveronRightBig'
import { CheveronUp } from './CheveronUp'
import { CheveronUpBig } from './CheveronUpBig'
import { Clock } from './Clock'
import { ClockBig } from './ClockBig'
import { ClockBigFilled } from './ClockBigFilled'
import { ClockFilled } from './ClockFilled'
import { Copy } from './Copy'
import { CopyBig } from './CopyBig'
import { CopyBigFilled } from './CopyBigFilled'
import { CopyFilled } from './CopyFilled'
import { Cross } from './Cross'
import { CrossBig } from './CrossBig'
import { CrossBigFilled } from './CrossBigFilled'
import { CrossBoxed } from './CrossBoxed'
import { CrossCircle } from './CrossCircle'
import { CrossCircleBig } from './CrossCircleBig'
import { CrossCircleBigFilled } from './CrossCircleBigFilled'
import { CrossCircleFilled } from './CrossCircleFilled'
import { CrossFilled } from './CrossFilled'
import { Crown } from './Crown'
import { CrownBig } from './CrownBig'
import { CrownBigFilled } from './CrownBigFilled'
import { CrownFilled } from './CrownFilled'
import { Fire } from './Fire'
import { FireBig } from './FireBig'
import { FireBigFilled } from './FireBigFilled'
import { FireFilled } from './FireFilled'
import { Gift } from './Gift'
import { GiftBig } from './GiftBig'
import { GiftBigFilled } from './GiftBigFilled'
import { GiftFilled } from './GiftFilled'
import { Growth } from './Growth'
import { GrowthBig } from './GrowthBig'
import { GrowthBigFilled } from './GrowthBigFilled'
import { GrowthFilled } from './GrowthFilled'
import { Heart } from './Heart'
import { HeartBig } from './HeartBig'
import { HeartBigFilled } from './HeartBigFilled'
import { HeartFilled } from './HeartFilled'
import { Hidden } from './Hidden'
import { HiddenBig } from './HiddenBig'
import { History } from './History'
import { HistoryBig } from './HistoryBig'
import { Info } from './Info'
import { InfoBig } from './InfoBig'
import { InfoBigFilled } from './InfoBigFilled'
import { InfoFilled } from './InfoFilled'
import { Key } from './Key'
import { KeyBig } from './KeyBig'
import { Lightning } from './Lightning'
import { LightningBig } from './LightningBig'
import { LightningBigFilled } from './LightningBigFilled'
import { LightningFilled } from './LightningFilled'
import { Loading } from './Loading'
import { Lock } from './Lock'
import { LockBig } from './LockBig'
import { LockBigFilled } from './LockBigFilled'
import { LockFilled } from './LockFilled'
import { Minus } from './Minus'
import { MinusBig } from './MinusBig'
import { MinusBigFilled } from './MinusBigFilled'
import { MinusFilled } from './MinusFilled'
import { NavigationBack } from './NavigationChevronLeft'
import { NavigationForward } from './NavigationChevronRight'
import { NavigationShare } from './NavigationShare'
import { Pencil } from './Pencil'
import { PencilBig } from './PencilBig'
import { PencilBigFilled } from './PencilBigFilled'
import { PencilFilled } from './PencilFilled'
import { Percentage } from './Percentage'
import { PercentageBadge } from './PercentageBadge'
import { PercentageBadgeBig } from './PercentageBadgeBig'
import { PercentageBadgeBigFilled } from './PercentageBadgeBigFilled'
import { PercentageBadgeFilled } from './PercentageBadgeFilled'
import { PercentageBig } from './PercentageBig'
import { PercentageBigFilled } from './PercentageBigFilled'
import { PercentageFilled } from './PercentageFilled'
import { Phone } from './Phone'
import { PhoneBig } from './PhoneBig'
import { PhoneBigFilled } from './PhoneBigFilled'
import { PhoneFilled } from './PhoneFilled'
import { PlusBigFilled } from './PlugBigFilled'
import { Plus } from './Plus'
import { PlusBig } from './PlusBig'
import { PlusFilled } from './PlusFilled'
import { Question } from './Question'
import { QuestionBig } from './QuestionBig'
import { QuestionBigFilled } from './QuestionBigFilled'
import { QuestionFilled } from './QuestionFilled'
import { Refresh } from './Refresh'
import { RefreshBig } from './RefreshBig'
import { RefreshBigFilled } from './RefreshBigFilled'
import { RefreshFilled } from './RefreshFilled'
import { Search } from './Search'
import { SearchBig } from './SearchBig'
import { SearchBigFilled } from './SearchBigFilled'
import { SearchFilled } from './SearchFilled'
import { Settings } from './Settings'
import { SettingsBig } from './SettingsBig'
import { SettingsBigFilled } from './SettingsBigFilled'
import { SettingsFilled } from './SettingsFilled'
import { Shown } from './Shown'
import { ShownBig } from './ShownBig'
import { ShownBigFilled } from './ShownBigFilled'
import { ShownFilled } from './ShownFilled'
import { Slider } from './Slider'
import { SliderBig } from './SliderBig'
import { SliderBigFilled } from './SliderBigFilled'
import { SliderFilled } from './SliderFilled'
import { Smartwatch } from './Smartwatch'
import { SmartwatchBig } from './SmartwatchBig'
import { SmartwatchBigFilled } from './SmartwatchBigFilled'
import { SmartwatchFilled } from './SmartwatchFilled'
import { Spark } from './Spark'
import { SparkBig } from './SparkBig'
import { Star } from './Star'
import { StarBig } from './StarBig'
import { StarBigFilled } from './StarBigFilled'
import { StarFilled } from './StarFilled'
import { StatsDown } from './StatsDown'
import { StatsDownBig } from './StatsDownBig'
import { StatsUp } from './StatsUp'
import { StatsUpBig } from './StatsUpBig'
import { Steps } from './Steps'
import { StepsBig } from './StepsBig'
import { Stopwatch } from './Stopwatch'
import { StopwatchBig } from './StopwatchBig'
import { StopwatchBigFilled } from './StopwatchBigFilled'
import { StopwatchFilled } from './StopwatchFilled'
import { Sweat } from './Sweat'
import { SweatBig } from './SweatBig'
import { Sweatcoin } from './Sweatcoin'
import { SweatcoinBig } from './SweatcoinBig'
import { Sync } from './Sync'
import { SyncBig } from './SyncBig'
import { Tag } from './Tag'
import { TagBig } from './TagBig'
import { TagBigFilled } from './TagBigFilled'
import { TagFilled } from './TagFilled'
import { Thermometer } from './Thermometer'
import { ThermometerBig } from './ThermometerBig'
import { ThermometerBigFilled } from './ThermometerBigFilled'
import { ThermometerFilled } from './ThermometerFilled'
import { ThreeDots } from './ThreeDots'
import { Tick } from './Tick'
import { TickBadge } from './TickBadge'
import { TickBadgeBig } from './TickBadgeBig'
import { TickBadgeBigFilled } from './TickBadgeBigFilled'
import { TickBadgeFilled } from './TickBadgeFilled'
import { TickBig } from './TickBig'
import { TickBoxed } from './TickBoxed'
import { TickCircle } from './TickCircle'
import { TickCircleBig } from './TickCircleBig'
import { TickCircleBigFilled } from './TickCircleBigFilled'
import { TickCircleFilled } from './TickCircleFilled'
import { Trophy } from './Trophy'
import { TrophyBig } from './TrophyBig'
import { Unlock } from './Unlock'
import { UnlockBig } from './UnlockBig'
import { UnlockBigFilled } from './UnlockBigFilled'
import { UnlockFilled } from './UnlockFilled'
import { IconFilling, IconSize, IconType } from './icons/consts'
import { Colors } from './Colors'

const icons = {}

interface Props {
  testID?: string
  type: IconType
  color?: string
  filling?: IconFilling
  size?: IconSize
}

const Icon: React.FC<Props> = ({
  testID,
  type,
  color = Colors.white,
  filling = IconFilling.OUTLINE,
  size = IconSize.SMALL,
}: Props) => {
  if (icons[type]) {
    const Component = icons?.[type]?.[size]
      ? icons[type][size][filling]
        ? icons[type][size][filling]
        : icons[type][size]
      : icons[type]

    return <Component testID={testID} color={color} />
  }

  console.error(`Couldn't find icon with given type ${type}`)

  return null
}

export default Icon
